---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test-env
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000