---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000