---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: prod-env
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080